### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gtnoble** [omnister/savitskygolay#1]
I'd like to incorporate this code into a project, but I don't see any license indicating that this is possible. Could you perhaps add a permissive license like MIT?

**Comment by omnister** [comment]
Would GPL be ok for you?  I can copy over the license boiler plate from another of my projects.  I don't have any problem with you using the code for any purpose, but I understand a license makes it easier for you to use.

kind regards,  Rick Walker walker AT omnisterra DOT com

**Comment by gtnoble** [comment]
Would you mind something like MIT license? This would allow for the
greatest number of people to use the code in their projects.

**Comment by omnister** [comment]
I changed the README to state this is released under MIT license.  I also changed the copyright text listed with the -l command line option to give the text of the MIT license along with copyright statements.

**Comment by gtnoble** [comment]
Wonderful, Thanks!
